### ISSUE TITLE
Comparison with predpatt?

### ISSUE THREAD

**Issue by LifeIsStrange** [yzhangcs/crfsrl#2]
Hi, I truly believe dependency parsing has a huge potential for semantic role labeling/information extraction.
Predpatt is some intersting prior work and I wonder how they compare on precision/recall, please benchmark!
https://www.cs.jhu.edu/~s.zhang/assets/pdf/iwcs17.pdf

Moreover, regarding a way to further increase accuracy, I wonder if you could leverage [Enhanced dependencies](https://universaldependencies.org/u/overview/enhanced-syntax.html) which predpatt unfortunately do not make use of.. despite their impressive expressive power.
@yzhangcs

**Comment by yzhangcs** [comment]
@LifeIsStrange Hi, thank you for recommending this work to me, which I was not aware of before.
I have just spent some time getting to know this paper, and do think it's very interesting. However, I don't think this is a suitable benchmark for my paper, as Predpatt makes use of gold UD treebanks while my approach is fully end-to-end, taking dependency trees as latent annotations. In contrast, I think a more comparable work is [Shi et al. 2020](https://aclanthology.org/2020.emnlp-main.610/).
Thank you for your suggestions!
