### ISSUE TITLE
Error while generating ConLL dataset objects for training the model

### ISSUE THREAD

**Issue by sanchit-ahuja** [yzhangcs/crfsrl#4]
Hi,

I have been getting an assertion error when trying to generate data for the ConLL training. 

```
Converting data/conll05/train.prop to conllu format
  0%|                                                                          | 49/989860 [00:01<9:20:53, 29.41it/s]
Traceback (most recent call last):
  File "scripts/prop2conllu.py", line 76, in <module>
    process(args.prop, args.file)
  File "scripts/prop2conllu.py", line 61, in process
    sentences.append(prop2conllu(lines[start:i]))
  File "scripts/prop2conllu.py", line 41, in prop2conllu
    assert len(prds) == len(args)
AssertionError
```
Can you please have a look at this? 
The command that I used to run the script: `bash scripts/conll05.sh PTB=ptb SRL=data`

**Comment by yzhangcs** [comment]
@sanchit-ahuja Hi, can you show me some sentence examples?

**Comment by yzhangcs** [comment]
@sanchit-ahuja Sorry for my late reply. I can not figure out what's wrong without further details. 
If you wish, please email me privately so that I can send you the data I've processed.

**Comment by sanchit-ahuja** [comment]
Sure @yzhangcs, I will email you. Closing this issue.
